### ISSUE TITLE
Can you provide a multi-head version of point transformer layer?

### ISSUE THREAD

**Issue by HankerWu** [lucidrains/point-transformer-pytorch#12]
FYI

**Comment by lucidrains** [comment]
Sure, I think it is possible to do

**Comment by lucidrains** [comment]
@HankerWu let me know if this works https://github.com/lucidrains/point-transformer-pytorch/blob/0.1.1/point_transformer_pytorch/multihead_point_transformer_pytorch.py#L31

**Comment by HankerWu** [comment]
Thanks for your work! It works well.
